sudo: required

services:
  - docker

before_install:
  - gem install bundler
  - docker build -t psalgaocar/docker-react -f Dockerfile.dev .

script:
  - docker run psalgaocar/docker-react npm run test -- --coverage